apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-k8s # name of the resource
spec:
  acme:
    # URL of ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    # E-mail address used for ACME registration
    email: cynomart@gmail.com
    # Name of a secret used to store the ACME account's private key
    privateKeySecretRef:
      name: letsencrypt-k8s
    # Activate the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
